# -*- coding: utf-8 -*-
"""inventory-time-series-focasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fr0iY5Nr9gzOcUtJl4WbJe_D25n6bao9

# Data Preprocessing
"""

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
sns.set_style("white")

df = pd.read_csv("sales_data.csv")

df.head()

df.dtypes

df=df[df['Store ID']=='S001']

df=df[df['Category']=='Groceries']
df['Product ID'].unique()

df=df[df['Product ID']=='P0005']
df.shape

df = df.sort_values("Date").reset_index(drop=True)

## date range
df['Date'].min(), df['Date'].max()

## check for duplicated dates
print(df['Date'].duplicated().sum())

print(df["Date"].dtype)

df["Date"].head()

## convert the data type to datetime
df["Date"] = pd.to_datetime(df["Date"])
print(df["Date"].dtype)

full_range = pd.date_range(df["Date"].min(),
                           df["Date"].max(),
                           freq="D")

missing_dates = full_range.difference(df["Date"])

## check if there are any missing dates
print(len(missing_dates))

"""# Problem Diagnosis"""

## check on stockout days (Inventory Level == 0):
df[df["Inventory Level"] == 0][["Date", "Units Sold", "Demand", "Inventory Level"]]

## total demand on stockout days
print(df[df["Inventory Level"] == 0]["Demand"].sum())
print(df["Demand"].sum())

## total unmet demand
df["Unmet Demand"] = df["Demand"] - df["Units Sold"]
df["Unmet Demand"] = (df["Demand"] - df["Units Sold"]).clip(lower=0)
total_unmet = df["Unmet Demand"].sum()
print(df['Unmet Demand'].min())
print(total_unmet)

## percentage of unmet demand
unmet_pct = total_unmet / df["Demand"].sum() * 100
print(unmet_pct)

unmet_days = (df["Unmet Demand"] > 0).sum()
print(f"Days with unmet demand: {unmet_days}")
print(f"Percentage of days: {100 * unmet_days / len(df):.2f}%")

## create a Pandas series with "Date" as the index
ts = df.set_index("Date")["Demand"]

## set the frequency as daily: the dates need even spacing as some time series models assume the gap between observations is constant
ts = ts.asfreq("D")
ts.head()

"""# EDA"""

from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller

"""### Decomposition & stationary"""

df['Demand'].describe()

ts.plot(figsize=(15,5))
plt.title("Daily Demand")
plt.show()

## split the series into 3 components: trend, seasonality, residual
decomposition = seasonal_decompose(ts, model="additive",period=7)

## plot the raw demain data, trend, seasonality, and residuals
fig = decomposition.plot()
fig.set_size_inches(12, 9)
plt.tight_layout()
plt.show()

print("Demand std:", ts.std())
print("Seasonal std:", decomposition.seasonal.std())
print("Residual std:", decomposition.resid.std())

rolling_mean = ts.rolling(7).mean()
rolling_std = ts.rolling(7).std()

plt.figure(figsize=(18,5))

plt.plot(ts, label="Demand")
plt.plot(rolling_mean, label="7-day Rolling Mean")
plt.plot(rolling_std, label="7-day Rolling Std")

plt.legend()
plt.show()

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

## ACF
plt.figure(figsize=(20,5))
plot_acf(ts.dropna(), lags=30)
plt.show()

## PACF
plt.figure(figsize=(20,5))
plot_pacf(ts.dropna(), lags=30)
plt.show()

## ADF test to check if the series is stationary or not
adf_result = adfuller(ts.dropna())
print("ADF Statistic:", round(adf_result[0],5))
print("p-value:", round(adf_result[1],5))
print("Stationary" if adf_result[1] < 0.05 else "Non-stationary")

## outliers
plt.figure(figsize=(8,4))
plt.boxplot(ts.dropna())
plt.title("Demand Distribution")
plt.show()

"""### Correlation"""

df[["Units Sold",
     "Demand",
     "Inventory Level"
     ]].corr()

corr = df[
    ["Demand",
     "Discount",
     "Promotion",
     "Epidemic"]].corr()

print(corr)

## plotting the heatmap for correlation
ax = sns.heatmap(corr, annot=True)

## check if the trends correspond to epidemic or holidays
epidemic_dates = df.loc[df["Epidemic"] == 1, "Date"]
print(f"Epidemic days: {len(epidemic_dates)}")
print(f"Epidemic date range: {epidemic_dates.min()} to {epidemic_dates.max()}")

## Average demand: epidemic vs non-epidemic
df.groupby("Epidemic")["Demand"].mean()

## Average demand: promotion vs no promotion
df.groupby("Promotion")["Demand"].mean()

## Average demand: discount vs no discount
df.groupby("Discount")["Demand"].mean()

## Correlation discount vs. promotion
df.groupby("Discount")["Promotion"].mean()

## day-of-week pattern avg demand
df["day_of_week"] = df["Date"].dt.day_name()

dow_order = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
dow_avg = df.groupby("day_of_week")["Demand"].mean().reindex(dow_order)

plt.figure(figsize=(7, 4.5))
ax = dow_avg.plot(kind="bar")
ax.bar_label(
    ax.containers[0],
    labels=[f"{x:.1f}" for x in dow_avg],
    padding=-0.5)
plt.title("Average Demand by Day of Week")
plt.ylabel("Avg Demand")
plt.xlabel("Day of Week")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

## seasonality (calendar season: Winter/Spring/Summer/Fall) avg demand
season_avg = df.groupby("Seasonality")["Demand"].mean().sort_values(ascending=False)

## weather condition avg demand
weather_avg = df.groupby("Weather Condition")["Demand"].mean().sort_values(ascending=False)

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
## Seasonality
season_avg.plot(kind="bar", ax=axes[0])

axes[0].set_title("Average Demand by Seasonality")
axes[0].set_ylabel("Average Demand")
axes[0].tick_params(axis="x", rotation=0)

# add values above bars
for i, v in enumerate(season_avg):
    axes[0].text(i, v + 1, f"{v:.1f}",
                 ha="center", fontsize=9)

## Weather
weather_avg.plot(kind="bar", ax=axes[1])

axes[1].set_title("Average Demand by Weather")
axes[1].set_ylabel("Average Demand")
axes[1].tick_params(axis="x", rotation=0)

# add values above bars
for i, v in enumerate(weather_avg):
    axes[1].text(i, v + 1, f"{v:.1f}",
                 ha="center", fontsize=9)

plt.tight_layout()
plt.show()

## counts, so we know if any category is rare (small sample, less reliable average)

## Seasonality counts:
print(df["Seasonality"].value_counts())

## Weather Condition counts:
print(df["Weather Condition"].value_counts())

"""# Train-test split"""

## split
train_end = "2023-09-30"

train = df[df["Date"] <= train_end].copy()
test = df[df["Date"] > train_end].copy()

print(len(train), len(test))

"""# Model Fitting

## Seasonal Naive Model (Baseline)
"""

from sklearn.metrics import mean_absolute_error, mean_squared_error

## combine train + test into one continuous series (needed so early test dates
## can look back into train for their "7 days ago" value)
full = pd.concat([train, test]).sort_values("Date").reset_index(drop=True)

## seasonal naive: shift the Demand column by 7 rows (since data is daily with no gaps,
## row i-7 IS exactly "7 days ago")
full["naive_pred"] = full["Demand"].shift(7)

## split back out the test portion with its predictions attached
test = full[full["Date"] > train_end].copy()

test[["Date", "Demand", "naive_pred"]].head()

test[test['Date']=='2023-11-15']

naive_mae = round(mean_absolute_error(test["Demand"],
                          test["naive_pred"]),5)

naive_rmse = round(np.sqrt(mean_squared_error(test["Demand"],
                                        test["naive_pred"])),5)
naive_mape = round(np.mean(np.abs((test["Demand"] - test["naive_pred"]) / test["Demand"])) * 100,5)

results = []
results.append({"model": "Seasonal Naive", "MAE": naive_mae, "RMSE": naive_rmse, "MAPE": naive_mape})

results

fig, ax = plt.subplots(figsize=(16, 5))

ax.plot(test["Date"], test["Demand"], label="Actual", color="black", linewidth=1.5)
ax.plot(test["Date"], test["naive_pred"], label="Seasonal Naive forecast", color="tab:orange", linestyle="--", linewidth=1.5)

ax.set_title("Seasonal Naive vs Actual Demand — Test Set (P005, Store S001)")
ax.set_ylabel("Demand")
ax.set_xlabel("Date")
ax.legend()
plt.tight_layout()
plt.show()

"""## Holt-Winters Exponential Smoothing"""

from statsmodels.tsa.holtwinters import ExponentialSmoothing

ets_model = ExponentialSmoothing(
    train.set_index("Date")["Demand"],
    trend="add", # additive trend (bounded wander, not exponential growth)
    seasonal="add", # additive seasonality (weekly cycle we confirmed)
    seasonal_periods=7, # weekly seasonality
    damped_trend=True # dampens the trend so long-horizon forecasts don't run away
).fit()

print(ets_model.summary())

## forecast over the test horizon
ets_forecast = ets_model.forecast(len(test))

test["ets_pred"] = ets_forecast.values

ets_mae = round(mean_absolute_error(test["Demand"],
                          test["ets_pred"]),5)

ets_rmse = round(np.sqrt(mean_squared_error(test["Demand"],
                                        test["ets_pred"])),5)

ets_mape = round(np.mean(np.abs((test["Demand"] - test["ets_pred"]) / test["Demand"])) * 100,5)

results.append({"model": "ETS", "MAE": ets_mae, "RMSE": ets_rmse, "MAPE": ets_mape})

results

fig, ax = plt.subplots(figsize=(16, 5))

ax.plot(test["Date"], test["Demand"], label="Actual", color="black", linewidth=1.5)
ax.plot(test["Date"], test["ets_pred"], label="ETS forecast", color="tab:blue", linewidth=1.5)

ax.set_title("ETS vs Actual Demand — Test Set (P005, Store S001)")
ax.set_ylabel("Demand")
ax.set_xlabel("Date")
ax.legend()
plt.tight_layout()
plt.show()

"""## SARIMAX"""

from statsmodels.tsa.statespace.sarimax import SARIMAX

## step 1: Prepare exogenous regressors
## Promotion and Epidemic are already 0/1, keep as-is
## Weather Condition and Seasonality are categorical -> one-hot encode

exog_cols_numeric = ["Promotion", "Epidemic"]
exog_cols_categorical = ["Weather Condition", "Seasonality"]

def build_exog(data):
    numeric = data[exog_cols_numeric].reset_index(drop=True)
    categorical = pd.get_dummies(data[exog_cols_categorical], drop_first=True).reset_index(drop=True)
    return pd.concat([numeric, categorical], axis=1)

train_exog = build_exog(train)
test_exog = build_exog(test)

## make sure test has the same dummy columns as train (in case a category is missing in one)
test_exog = test_exog.reindex(columns=train_exog.columns, fill_value=0)
print(train_exog.head())

print(train_exog.dtypes)

## convert from boolean to float
train_exog = train_exog.astype(float)
test_exog = test_exog.astype(float)

print(train_exog.dtypes)

train_exog.index = train["Date"].values
test_exog.index = test["Date"].values

print(train_exog.index[:5])
print(train.set_index("Date")["Demand"].index[:5])  # should match in type/values

!pip install pmdarima --quiet
from pmdarima import auto_arima

auto_model = auto_arima(
    train.set_index("Date")["Demand"],
    exogenous=train_exog,
    seasonal=True,
    m=7, # weekly seasonality
    stepwise=True,
    trace=True,
    suppress_warnings=True
)

print(auto_model.summary()) ## find optimal orders for SARIMAX

## step 2: fit SARIMAX
sarimax_model = SARIMAX(
    train.set_index("Date")["Demand"],
    exog=train_exog,
    order=(1, 0, 2),
    seasonal_order=(0, 0, 0, 7),
    enforce_stationarity=False,
    enforce_invertibility=False
).fit(disp=False, maxiter=300, method='powell')

print(sarimax_model.summary())

sarimax_forecast = sarimax_model.forecast(steps=len(test), exog=test_exog)
test["sarimax_pred"] = sarimax_forecast.values

results.append({"model": "SARIMAX",
                "MAE": round(mean_absolute_error(test["Demand"], test["sarimax_pred"]), 5),
                "RMSE": round(np.sqrt(mean_squared_error(test["Demand"], test["sarimax_pred"])), 5),
                "MAPE": round(np.mean(np.abs((test["Demand"] - test["sarimax_pred"]) / test["Demand"])) * 100, 5)})

results

fig, ax = plt.subplots(figsize=(16, 5))

ax.plot(test["Date"], test["Demand"], label="Actual", color="black", linewidth=1.5)
ax.plot(test["Date"], test["sarimax_pred"], label="SARIMAX forecast", color="tab:green", linewidth=1.5)

ax.set_title("SARIMAX vs Actual Demand — Test Set (P005, Store S001)")
ax.set_ylabel("Demand")
ax.set_xlabel("Date")
ax.legend()
plt.tight_layout()
plt.show()

"""## XGBoost"""

import xgboost as xgb

## step 1: create time-series features
## since XGBoost doesn't model temporal patterns automatically like ETS and SARIMAX

df["lag_1"] = df["Demand"].shift(1)
df["lag_7"] = df["Demand"].shift(7)

df["rolling_mean_7"] = (df["Demand"].shift(1).rolling(7).mean())

df["day_of_week"] = df["Date"].dt.dayofweek
df["month"] = df["Date"].dt.month

df = pd.get_dummies(df,
                    columns=["Weather Condition", "Seasonality"],
                    drop_first=True)

df.columns

features = ["lag_1", "lag_7", "rolling_mean_7", "day_of_week", "month", "Promotion", "Epidemic",
            'Weather Condition_Rainy', 'Weather Condition_Snowy',
            'Weather Condition_Sunny', 'Seasonality_Spring', 'Seasonality_Summer','Seasonality_Winter']

train_xgb = df[df["Date"] <= train_end]
test_xgb = df[df["Date"] > train_end]

X_train = train_xgb[features]
y_train = train_xgb["Demand"]

X_test = test_xgb[features]
y_test = test_xgb["Demand"]

xgb_model = xgb.XGBRegressor(n_estimators=300,
                             max_depth=4,
                             learning_rate=0.05,
                             random_state=42)

xgb_model.fit(X_train, y_train)

xgb_preds = xgb_model.predict(X_test)
test["xgb_pred"] = xgb_preds

results.append({"model": "XGBoost",
                "MAE": round(mean_absolute_error(test["Demand"], test["xgb_pred"]), 5),
                "RMSE": round(np.sqrt(mean_squared_error(test["Demand"], test["xgb_pred"])), 5),
                "MAPE": round(np.mean(np.abs((test["Demand"] - test["xgb_pred"]) / test["Demand"])) * 100, 5)})

## feature importance
importance = pd.Series(xgb_model.feature_importances_, index=X_train.columns).sort_values(ascending=False)
print(importance)

importance.plot(kind="barh", figsize=(8, 6))
plt.title("XGBoost Feature Importance")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

fig, ax = plt.subplots(figsize=(16, 5))

ax.plot(test["Date"], test["Demand"], label="Actual", color="black", linewidth=1.5)
ax.plot(test["Date"], test["xgb_pred"], label="XGBoost forecast", color="tab:purple", linewidth=1.5)

ax.set_title("XGBoost vs Actual Demand — Test Set (P005, Store S001)")
ax.set_ylabel("Demand")
ax.set_xlabel("Date")
ax.legend()
plt.tight_layout()
plt.show()

results

"""# Monte Carlo Simulations

### Demand Simulations
"""

## residuals = actual - predicted, on the test set
test["sarimax_resid"] = test["Demand"] - test["sarimax_pred"]

test["sarimax_resid"].describe()

fig, axes = plt.subplots(1, 2, figsize=(11, 4))

## histogram of residuals
axes[0].hist(test["sarimax_resid"], bins=25, edgecolor="black")
axes[0].axvline(0, color="red", linestyle="--")
axes[0].set_title("Distribution of SARIMAX Residuals (Test Set)")
axes[0].set_xlabel("Residual")

## residuals over time
axes[1].plot(test["Date"], test["sarimax_resid"])
axes[1].axhline(0, color="red", linestyle="--")
axes[1].set_xlabel("Date")
axes[1].tick_params(axis="x", rotation=40)
axes[1].set_title("Residuals Over Time")
axes[1].set_xlabel("Date")

plt.tight_layout()
plt.show()

from scipy import stats

plt.figure(figsize=(6, 6))

stats.probplot(
    test["sarimax_resid"],
    dist="norm",
    plot=plt
)

plt.title("Q-Q Plot of SARIMAX Residuals")
plt.xlabel("Theoretical Quantiles")
plt.ylabel("Sample Quantiles")

plt.tight_layout()
plt.show()

n_simulations = 1000
horizon = 60  # simulate 60 days ahead

## use SARIMAX to forecast the demands for the next 60 days beyond the end of test
## simulate the residuals for the next 60 days
## simulated actual demand = simulated residuals + SARIMAX forecasted demand

future_dates = pd.date_range(test["Date"].max() + pd.Timedelta(days=1), periods=horizon, freq="D")
print(future_dates)

## update SARIMAX with the test set
sarimax_extended = sarimax_model.append(test.set_index("Date")["Demand"],
                                        exog=test_exog)

### SCENARIO 1: No Promotion
## Promotion = 0 every day (no promotion)
no_promo_promotion = np.zeros(horizon)

## Epidemic = test set's average value
no_promo_epidemic = np.full(horizon, test["Epidemic"].mean())

## build the exog table for this scenario
no_promo_exog = pd.DataFrame({"Promotion": no_promo_promotion,
                              "Epidemic": no_promo_epidemic,}, index=future_dates)

## Weather/Seasonality dummies: repeat the last known day from test
last_dummies = test_exog.iloc[-1].drop(["Promotion", "Epidemic"])
for col in last_dummies.index:
    no_promo_exog[col] = last_dummies[col]

## reorder the columns to match SARIMAX's training data
## then convert all values to float
no_promo_exog = no_promo_exog[train_exog.columns].astype(float)

## predict the next 60-day period
no_promo_forecast = sarimax_extended.get_forecast(steps=horizon, exog=no_promo_exog).predicted_mean

print(f"No Promotion: {no_promo_forecast.mean():.1f} units/day")

### SCENARIO 2: Weekly Promotion
## Promotion = 1 every 7th day, 0 otherwise
weekly_promo_promotion = np.tile([1] + [0]*6, horizon // 7 + 1)[:horizon]

weekly_promo_epidemic = np.full(horizon, test["Epidemic"].mean())
weekly_promo_exog = pd.DataFrame({"Promotion": weekly_promo_promotion,
                                  "Epidemic": weekly_promo_epidemic,}, index=future_dates)

for col in last_dummies.index:
    weekly_promo_exog[col] = last_dummies[col]

weekly_promo_exog = weekly_promo_exog[train_exog.columns].astype(float)

## SARIMAX's forecast
weekly_promo_forecast = sarimax_extended.get_forecast(steps=horizon, exog=weekly_promo_exog).predicted_mean

print(f"Weekly Promotion: {weekly_promo_forecast.mean():.1f} units/day")

np.random.seed(42)

residual_pool = test["sarimax_resid"].values  # SARIMAX's actual observed test-set errors

## simulations using bootstrap resampling since the residuals are not completely normally distributed
## the distribution is unknown
simulated_residuals_no_promo = np.random.choice(residual_pool, size=(n_simulations, horizon), replace=True)
simulated_demand_no_promo = no_promo_forecast.values[np.newaxis, :] + simulated_residuals_no_promo

simulated_demand_no_promo = np.clip(simulated_demand_no_promo, a_min=0, a_max=None) ## prevent demand < 0

simulated_residuals_weekly = np.random.choice(residual_pool, size=(n_simulations, horizon), replace=True)
simulated_demand_weekly = weekly_promo_forecast.values[np.newaxis, :] + simulated_residuals_weekly

simulated_demand_weekly = np.clip(simulated_demand_weekly, a_min=0, a_max=None) ## prevent demand < 0

print(f"No Promotion: mean total demand = {simulated_demand_no_promo.sum(axis=1).mean():.0f}")
print(f"Weekly Promotion: mean total demand = {simulated_demand_weekly.sum(axis=1).mean():.0f}")
## sum across 60 days
## then take the average of 1000 simulated paths

plt.figure(figsize=(12,5))

plt.plot(
    simulated_demand_no_promo.mean(axis=0),
    label="No Promotion")

plt.plot(
    simulated_demand_weekly.mean(axis=0),
    label="Weekly Promotion")

plt.xlabel("Day")
plt.ylabel("Expected Demand")
plt.title("Demand Under Different Promotion Scenarios")
plt.legend()
plt.show()

"""### Inventory Simulations"""

## create function for inventory simulations
def simulate_inventory(demand_paths, starting_inventory, lead_time, policy):

    n_simulations, horizon = demand_paths.shape
    ending_inventory = []

    stockout_count = 0
    total_stockout_days = 0

    for sim in range(n_simulations):
        inventory = starting_inventory
        pending_order = None
        had_stockout = False

        for day in range(horizon):
            # 1. Receive order if it arrives today
            if pending_order is not None:
                if pending_order["arrival_day"] == day:
                    inventory += pending_order["quantity"]
                    pending_order = None

            # 2. Today's demand
            demand = demand_paths[sim, day]
            if demand > inventory:
                # stockout happens
                had_stockout = True
                total_stockout_days += 1
                inventory = 0
            else:
                inventory -= demand

            # 3. Place order according to policy
            if policy["type"] == "periodic": ## policy A
                if day % policy["interval"] == 0:
                    pending_order = {
                        "arrival_day": day + lead_time,
                        "quantity": policy["order_qty"]}

            elif policy["type"] == "reorder_point": ## policy B
                if inventory < policy["s"]:
                    order_quantity = policy["S"] - inventory
                    pending_order = {
                        "arrival_day": day + lead_time,
                        "quantity": order_quantity}

        if had_stockout:
            stockout_count += 1

        ending_inventory.append(inventory)

    return {
        "percent_simulations_with_stockout": stockout_count / n_simulations * 100,
        "average_daily_stockout_rate": total_stockout_days / (n_simulations*horizon),
        "average_ending_inventory": np.mean(ending_inventory)
}

starting_inventory = df["Inventory Level"].iloc[-1] # use the most recent inventory level as the intial inventory level value for the simulation
lead_time = 1 # number of days the products will be delivered after ordering

avg_daily_demand_no_promo = no_promo_forecast.mean()
avg_daily_demand_weekly = weekly_promo_forecast.mean()

resid_std = test["sarimax_resid"].std() # use to compute safety stock

### Policy A: Order a quantity = avg daily demand*5 for a fixed period of every 5 days
policy_a_no_promo = {"type": "periodic", "interval": 5, "order_qty": avg_daily_demand_no_promo*5}
policy_a_weekly = {"type": "periodic", "interval": 5, "order_qty": avg_daily_demand_weekly*5}

### Policy B: When inventory level drops below a threshold, order enough up to a target value
policy_b_no_promo = {"type": "reorder_point",
                     "s": avg_daily_demand_no_promo * lead_time + 1.65 * resid_std,
                     "S": avg_daily_demand_no_promo * 5}

policy_b_weekly = {"type": "reorder_point",
                   "s": avg_daily_demand_weekly * lead_time + 1.65 * resid_std,
                   "S": avg_daily_demand_weekly * 5}

# threshold = expected demand during lead time + resid_std * k
# resid_std * k = safety buffer
# k = 1.65 = the value below which ~95% of a normal distribution falls (i.e., stockout risk of ~5%)

sim_results = {}

## No Promotion scenario
sim_results["No Promotion - Policy A"] = simulate_inventory(simulated_demand_no_promo, starting_inventory, lead_time, policy_a_no_promo)
sim_results["No Promotion - Policy B"] = simulate_inventory(simulated_demand_no_promo, starting_inventory, lead_time, policy_b_no_promo)

## Weekly Promotion scenario
sim_results["Weekly Promotion - Policy A"] = simulate_inventory(simulated_demand_weekly, starting_inventory, lead_time, policy_a_weekly)
sim_results["Weekly Promotion - Policy B"] = simulate_inventory(simulated_demand_weekly, starting_inventory, lead_time, policy_b_weekly)

for policy, result in sim_results.items():
    print(policy)
    print(f"  % simulations with stockout: {result['percent_simulations_with_stockout']:.3f}%")
    print(f"  Average daily stockout rate: {result['average_daily_stockout_rate']*100:.3f}%")
    print(f"  Average ending inventory: {result['average_ending_inventory']:.2f}")
    print()

"""### Sensitivity Analysis"""

## Policy A (vary safety buffer %, fixed interval)
buffer_pcts_to_test = [-0.15, -0.10, -0.05, 0]
fixed_interval = 1  # reorder daily

policy_a_buffer_sensitivity = []

for buffer_pct in buffer_pcts_to_test:
    for scenario_name, demand_paths, avg_demand in [
        ("No Promotion", simulated_demand_no_promo, avg_daily_demand_no_promo),
        ("Weekly Promotion", simulated_demand_weekly, avg_daily_demand_weekly),
    ]:
        order_qty = avg_demand * fixed_interval * (1 + buffer_pct)
        policy = {"type": "periodic", "interval": fixed_interval, "order_qty": order_qty}
        result = simulate_inventory(demand_paths, starting_inventory, lead_time, policy)

        policy_a_buffer_sensitivity.append({
            "Policy": "A",
            "Scenario": scenario_name,
            "Buffer %": buffer_pct * 100,
            "Order Qty": round(order_qty, 1),
            "Stockout %": round(result["percent_simulations_with_stockout"], 2),
            "Avg Ending Inventory": round(result["average_ending_inventory"], 1),
        })

policy_a_buffer_df = pd.DataFrame(policy_a_buffer_sensitivity)
print(policy_a_buffer_df[["Scenario",'Buffer %', 'Order Qty','Stockout %','Avg Ending Inventory']])

## Policy B (vary reorder threshold s, keep S fixed)
# s is currently: avg_demand * lead_time + k * resid_std, where k=1.65 (a ~95% service-level z-score)
# Let's vary k instead of an absolute number, since it's more interpretable (bigger k = bigger safety margin)

k_values_to_test = [0.5, 1.0, 1.65, 2.0, 2.33]  # roughly corresponds to ~70%, ~84%, ~95%, ~98%, ~99% service levels
fixed_S_days = 5  # hold target level constant while we vary the threshold

policy_b_threshold_sensitivity = []

for k in k_values_to_test:
    for scenario_name, demand_paths, avg_demand in [
        ("No Promotion", simulated_demand_no_promo, avg_daily_demand_no_promo),
        ("Weekly Promotion", simulated_demand_weekly, avg_daily_demand_weekly),
    ]:
        s_value = avg_demand * lead_time + k * resid_std
        policy = {
            "type": "reorder_point",
            "s": s_value,
            "S": avg_demand * fixed_S_days
        }
        result = simulate_inventory(demand_paths, starting_inventory, lead_time, policy)

        policy_b_threshold_sensitivity.append({
            "Policy": "B",
            "Scenario": scenario_name,
            "k (safety factor)": k,
            "s (threshold)": round(s_value, 1),
            "Stockout %": round(result["percent_simulations_with_stockout"], 2),
            "Avg Ending Inventory": round(result["average_ending_inventory"], 1),
        })

policy_b_threshold_df = pd.DataFrame(policy_b_threshold_sensitivity)
print(policy_b_threshold_df[['Scenario','k (safety factor)', 's (threshold)','Stockout %','Avg Ending Inventory']])

fig, axes = plt.subplots(1, 2, figsize=(10, 5))

## Policy A
for scenario_name in ["No Promotion", "Weekly Promotion"]:
    subset = policy_a_buffer_df[policy_a_buffer_df["Scenario"] == scenario_name]
    axes[0].plot(
        subset["Buffer %"],
        subset["Stockout %"],
        marker="o",
        label=scenario_name
    )

axes[0].set_xlabel("Safety Buffer (%)")
axes[0].set_ylabel("Stockout Risk (%)")
axes[0].set_title("Policy A: Stockout Risk vs Safety Buffer")
axes[0].legend()
axes[0].grid(alpha=0.3)


## Policy B
for scenario_name in ["No Promotion", "Weekly Promotion"]:
    subset = policy_b_threshold_df[policy_b_threshold_df["Scenario"] == scenario_name]
    axes[1].plot(
        subset["k (safety factor)"],
        subset["Stockout %"],
        marker="o",
        label=scenario_name
    )

axes[1].set_xlabel("Safety Factor k")
axes[1].set_ylabel("Stockout Risk (%)")
axes[1].set_title("Policy B: Stockout Risk vs Safety Factor")
axes[1].legend()
axes[1].grid(alpha=0.3)


plt.tight_layout()
plt.show()

## policy comparison: no promotion
policy_a_np = policy_a_buffer_df[policy_a_buffer_df["Scenario"] == "No Promotion"]
policy_b_np = policy_b_threshold_df[policy_b_threshold_df["Scenario"] == "No Promotion"]

plt.figure(figsize=(6,6))

# Policy A
plt.scatter(
    policy_a_np["Avg Ending Inventory"],
    policy_a_np["Stockout %"],
    s=100,
    label="Policy A"
)

for i,row in policy_a_np.iterrows():
    plt.annotate(
        f"A {row['Buffer %']}%",
        (row["Avg Ending Inventory"], row["Stockout %"]),
        xytext=(5,5),
        textcoords="offset points"
    )


# Policy B
plt.scatter(
    policy_b_np["Avg Ending Inventory"],
    policy_b_np["Stockout %"],
    s=100,
    label="Policy B"
)

for i,row in policy_b_np.iterrows():
    plt.annotate(
        f"B k={row['k (safety factor)']}",
        (row["Avg Ending Inventory"], row["Stockout %"]),
        xytext=(5,5),
        textcoords="offset points"
    )


plt.xlabel("Average Ending Inventory")
plt.ylabel("Stockout Probability (%)")
plt.title("Inventory Policy Efficiency Comparison (No Promotion)")
plt.legend()
plt.grid(True)
plt.show()

## policy comparison: weekly promotion
policy_a_promo = policy_a_buffer_df[policy_a_buffer_df["Scenario"] == "Weekly Promotion"]
policy_b_promo = policy_b_threshold_df[policy_b_threshold_df["Scenario"] == "Weekly Promotion"]

plt.figure(figsize=(6,6))

# Policy A
plt.scatter(
    policy_a_promo["Avg Ending Inventory"],
    policy_a_promo["Stockout %"],
    s=100,
    label="Policy A"
)

for i,row in policy_a_promo.iterrows():
    plt.annotate(
        f"A {row['Buffer %']}%",
        (row["Avg Ending Inventory"], row["Stockout %"]),
        xytext=(5,5),
        textcoords="offset points"
    )


# Policy B
plt.scatter(
    policy_b_promo["Avg Ending Inventory"],
    policy_b_promo["Stockout %"],
    s=100,
    label="Policy B"
)

for i,row in policy_b_promo.iterrows():
    plt.annotate(
        f"B k={row['k (safety factor)']}",
        (row["Avg Ending Inventory"], row["Stockout %"]),
        xytext=(5,5),
        textcoords="offset points"
    )


plt.xlabel("Average Ending Inventory")
plt.ylabel("Stockout Probability (%)")
plt.title("Inventory Policy Efficiency Comparison (Weekly Promotion)")
plt.legend()
plt.grid(True)
plt.show()